### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by BitShard**
Updated to be compatible with PluggableAuth >=6.0. I have only tested the changes lightly, I lack a rigorous test environment, and at the moment I don't have the time to set one up. I am happy to make additional changes if any errors persist, though!

### CODE REVIEW

**Comment by mdoggydog** [comment]
Thanks for the PR.  FYI, it will be little while (couple months) before getting to it.  Our system is still on PluggableAuth 5.7, and likely will stay that way until we begin contemplating switching to MW 1.39 (the next LTS release) which is expected to be released in November.  Also, I am in the midst of adding some new features/refactors which I want to make available for PA 5.7 users; so, those need to land first.

**Comment by djlambert** [comment]
Any progress on this? Was hoping to use this with a fresh install of 1.39

**Comment by djlambert** [comment]
I merged these changes into my own fork. Adding the following to my `LocalSettings.php` appears to have activated the extension, and I was able to login:
```php
$wgPluggableAuth_Config[] = [
        'plugin' => 'DiscourseSsoConsumer',
        'data' => []
];
```
So there's still some work to do handling the new config from PluggableAuth 6.0+. My PHP is extremely rusty, and a lot has changed since 5.3 🤣, else I'd make an attempt myself 🤷.

**Comment by mdoggydog** [comment]
I'm sorry to say it's likely going to be another couple of months (realizing that 2x "couple months" has already transpired), mostly because the new features/refactors hit some snags and then other tasks pushed this to a back-burner.

The sequence of events will go something like this:
 * We release v3.0.0, with features/refactors, for PluggableAuth 5.x and MW 1.35.x.
 * We start migrating DiscourseSsoConsumer to PA 6.x and MW 1.39.
 * We spin up a validation environment to confirm that all the extensions we need work (together) with MW 1.39.
 * We release v4.0.0 which works with PA 6.x and MW 1.39.

(E.g., Semantic Mediawiki finally came out with a MW-1.39-compatible version 30 days ago, so there was no reason for us to even look at MW 1.39 before that, and we aren't going to release a MW-1.39-compatible version of DSsoC before we are using it ourselves because it would be too onerous to try to support/maintain something that we don't use ourselves.)

**Comment by uckelman** [comment]
Following this with great interest. We're likely to be on MW 1.38 sometime in the near future, so I'll be able to tell you how/whether the existing code works with that. MW 1.39, I can't say; if might be a while for us to get there.

**Comment by mdoggydog** [comment]
> I'm sorry to say it's likely going to be another couple of months

*Couple?  Ha!  It took six!*

I believe this is resolved now, with the release of version 4.0.0, which works with PluggableAuth 6.3.  It also appears to work with MediaWiki 1.39 --- though I have not exercised it extensively (as we are just now getting around to working on our 1.35->1.39 transition).  I make no claims about MW 1.36-1.38.

As the release notes say, the jump from 2.0.3 to 3.0.0 is huge, but the change from 3.0.0 to 4.0.0 is just the choice of PluggableAuth.  (I think 3.0.0 also appeared to work with MW 1.39; exercised even less thoroughly.)

I'm not planning to contemplate PluggableAuth 7.x until after we have settled into using MW 1.39 (under PHP 8.2, since that is what Debian stable has transitioned to).

FYI, there is a feature ("SeamlessLogin") that requires a [patch to Discourse](https://github.com/discourse/discourse/pull/22393) that has not yet been accepted upstream, but I did not want to hold up the release of DiscourseSsoConsumer any longer just for that PR.  ("AutoRelogin" will also work better with that patch, but I think it will get the job done without it, too.)

**Comment by uckelman** [comment]
I'm planning to move to MW 1.39 next week; I'll let you know how it goes. I'm grateful for your efforts with this.

**Pull request closed without merging**
